thelibraryproject/thelibrary/Models/Author.cs
using System.ComponentModel.DataAnnotations;
using thelibrary.Data.enums;

namespace thelibrary.Models
{
    public class Author
    {
        [Key]
        public int Id { get; set; }
        
        //public string PictureURL { get; set; }
        public string Name { get; set; }
        public string? Biography { get; set; }
        public sex Sex { get; set; }

        //Relationship
        public ICollection<BookAuthor> BookAuthors { get; set; }

    }
}

thelibraryproject/thelibrary/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using thelibrary.Data;
using thelibrary.Models;
using thelibrary.Repository;
using thelibrary.Services;
using thelibrary.ViewModel;

namespace thelibrary.Controllers
{
    public class AuthorController : Controller
    {
        private readonly LibraryDbContext _dbContext;
        private readonly IAuthorRepository _authorRepository;
        private readonly IPhotoService _photoService;
        public AuthorController(LibraryDbContext dbContext, IAuthorRepository authorRepository, IPhotoService photoService)
        {
            this._dbContext = dbContext;
            this._authorRepository = authorRepository;
            this._photoService = photoService;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _authorRepository.GetAuthors();
            return View(data);
        }

        public async Task<IActionResult> UserIndex()
        {
            var data = await _authorRepository.GetAuthors();
            return View(data);
        }

        public async Task<IActionResult> Create()
        {
            var model = new AuthorViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuthorViewModel author)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Upload Failed");
                return View(author);
            }

            //var result = await _photoService.AddPhotoAsync(author.PictureURL);

            var newAuthor = new Author()
            {
               Biography = author.Biography,
               Name = author.Name,
               Sex = author.Sex,
               //PictureURL = result.Url.ToString(),
               Id = author.Id
                
            };
            _authorRepository.Add(newAuthor);

          
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Edit(int Id)
        {
            var getauthor = await _authorRepository.GetById(Id);
            if (getauthor == null) return View("Error");
            var newAuthor = new AuthorViewModel()
            {
                Biography = getauthor.Biography,
                Name = getauthor.Name,
                Sex = getauthor.Sex,
                //PictureURL = result.Url.ToString(),
                Id = getauthor.Id
            };

            return View(newAuthor);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AuthorViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Edit Failed");
                return View("Edit", model);
            }
            else
            {
                var author = await _authorRepository.GetById(model.Id);
                if (author != null)
                {
                    author.Id= model.Id;
                    author.Name = model.Name;
                    author.Biography = model.Biography;
                    author.Sex = model.Sex;

                    _authorRepository.Update(author);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }

            }

        }

        public IActionResult BookByAuthor(int Id)
        {
            var booksByAuthor = _dbContext.BookAuthors
            .Where(ba => ba.AuthorId == Id)
            .Include(ba => ba.Book)
            .ToList();
            //var author = _dbContext.BookAuthors.Include(c => c.Book).FirstOrDefault(c => c.Id == Id);
            return View(booksByAuthor);
        }

    }
}

thelibraryproject/thelibrary/Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using System.Net;
using thelibrary.Data;
using thelibrary.Map;
using thelibrary.Migrations;
using thelibrary.Models;
using thelibrary.Repository;
using thelibrary.Services;
using thelibrary.ViewModel;
using static System.Reflection.Metadata.BlobBuilder;

namespace thelibrary.Controllers
{
    public class BookController : Controller
    {
        private readonly LibraryDbContext _dbContext;
        private readonly IBookRepository _bookRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IPhotoService _photoService;
        private readonly IAuthorRepository _authorRepository;
        private readonly UserManager<Users> _userManager;

        public BookController(LibraryDbContext dbContext, UserManager<Users> userManager, IAuthorRepository authorRepository, IBookRepository bookRepository, IPhotoService photoService, ICategoryRepository categoryRepository)
        {
            this._dbContext = dbContext;
            this._bookRepository = bookRepository;
            this._photoService = photoService;
            this._categoryRepository = categoryRepository;
            this._authorRepository = authorRepository;
            this._userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            
            var data = _bookRepository.GetBooks();
                return View(data);                      
            
        }

        public async Task<IActionResult> UserIndex()
        {

            var data = _bookRepository.GetBooks();
            return View(data);

        }

        public IActionResult Search(string searchTerm)
        {
            var books = _dbContext.Books
                .Where(b => b.Title.Contains(searchTerm) || b.Category.Name.Contains(searchTerm))
                .ToList();

            return View("SearchResults", books);
        }


        public async Task<IActionResult> GetUserId()
        {
           return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetUserId(string username)
        {
            
                var user = await _userManager.FindByNameAsync(username);

                if (user != null)
                {
                    ViewBag.UserId = user.Id;
                }
                else
                {
                    ViewBag.UserId = null; // User not found
                }

                return View(); // Return to the same form view
            
        }
        public async Task<IActionResult> Detail(int Id)
        {
            var getBook = await _bookRepository.GetBookById(Id);
            return View(getBook);
        }       

        public async Task<IActionResult> Create()
        {
            var model =  new BookViewModel();
            
            var categories = await _categoryRepository.GetAllCategories();
            var authors = await _authorRepository.GetAuthors();
            ViewBag.category = new SelectList(categories.ToList(), "Id", "Name");
            ViewBag.author = new MultiSelectList(authors.ToList(), "Id", "Name");


            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> Create(BookViewModel  model) 
        {
           
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Upload Failed"); 
                return View(model);
            }
            
            var result = await _photoService.AddPhotoAsync(model.ActualBook);

            var newBook = new Book()
            {
                Title = model.Title,
                Pages = model.Pages,
                BookSummary = model.BookSummary,
                ActualBook = result.Url.ToString(),
                CategoryId = model.CategoryId,
                
                
            };
            _bookRepository.Add(newBook);
            //_dbContext.SaveChanges();

            foreach (var id in model.AuthorId)
            {
                var _book_author = new BookAuthor()
                {
                    BookId = newBook.Id,
                    AuthorId = id
                };
                _dbContext.BookAuthors.Add(_book_author);
                _dbContext.SaveChanges();
            }
            return RedirectToAction("Index");
                                        
            

        }
        //[Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> Edit(int Id)
        {
            var getBook = await _bookRepository.GetBookById(Id);
            if (getBook == null) return View("Error");
            var categories = await _categoryRepository.GetAllCategories();
            var authors = await _authorRepository.GetAuthors();
            ViewBag.category = new SelectList(categories.ToList(), "Id", "Name");
            ViewBag.author = new MultiSelectList(authors.ToList(), "Id", "Name");
            var bookVM = getBook.Mapper();            
            return View(bookVM);

        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditBookViewModel model, int Id)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Edit Failed");
                return View("Edit", model);
            }
            else
            {
                var book = await _bookRepository.GetBookById(Id);
                if (book != null)
                {
                    try
                    {

                        await _photoService.DeletePhotoAsync(book.ActualBook);
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", "Couldn't Delete photos");
                        return View(model);
                    }
                    var photoresult = await _photoService.AddPhotoAsync(model.ActualBook);

                    book.Id = model.Id;
                    book.Title = model.Title;
                    book.Pages = model.Pages;
                    book.BookSummary = model.BookSummary;
                    book.ActualBook = photoresult.Url.ToString();
                    book.CategoryId = model.CategoryId;

                    if(model.AuthorId != null)
                    {
                        foreach (var id in model.AuthorId)
                        {
                            var _book_author = new BookAuthor()
                            {
                                BookId = book.Id,
                                AuthorId = id
                            };
                            _dbContext.BookAuthors.Add(_book_author);
                            _dbContext.SaveChanges();
                        }

                    }
                    _dbContext.SaveChanges();
                    _bookRepository.Update(book);                  
                    return RedirectToAction("Index");
                    }
                else
                {
                    return View(model);
                }

            }            

        }
        public async Task<IActionResult> Borrow(int bookId)
        {
            var book = await _dbContext.BookReservations.
                Include(r => r.Book).
                Include(r => r.User).
                FirstOrDefaultAsync(x => x.BookId == bookId);
            //var book = await _dbContext.Books.FirstOrDefaultAsync(b=>b.Id == bookId);
            if (book == null)
            {
                return NotFound();
            }

            var Borrow = new BorrowBook
            {
                BookId = bookId,
                
            };

            return View(Borrow);
            
        }

        [HttpPost]
        public async Task<IActionResult> Borrow(BorrowBook borrow)
        {
            var book = await _dbContext.Books.FirstOrDefaultAsync(x => x.Id == borrow.BookId);
            var reservation = _dbContext.BookReservations
            .Include(r => r.User) // Include the user information
            .FirstOrDefault(r => r.BookId == borrow.BookId);


            if (book != null && book.IsReserved== true)
            {

                var borrowedbook = new BorrowBook
                {
                    BookId = borrow.BookId,
                    UserId = reservation.UserId, // Replace with actual user name
                    BorrowDate = DateTime.Now,
                    ReturnDate = DateTime.Now.AddDays(14)
                };

                book.IsReserved = true;
                book.IsBorrowed = true;
                _dbContext.Booksborrowed.Add(borrowedbook);  
                _dbContext.SaveChanges();
               

               
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Return(BorrowBook borrow)
        {
            var borrowed = await _dbContext.Booksborrowed.FirstOrDefaultAsync(x => x.BookId == borrow.BookId);
            var book = _dbContext.Books.FirstOrDefault(b => b.Id == borrowed.BookId);

            if (borrowed != null && book.IsBorrowed == true )
            {
                
                if (book != null)
                {
                    book.IsReserved = false;
                    book.IsBorrowed = false;
                    //_dbContext.Booksborrowed.Remove(borrow);
                    _dbContext.SaveChanges();


                }                
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Reserve(int bookId)
        {

            var book = await _dbContext.Books.FirstOrDefaultAsync(x => x.Id == bookId);            
            if (book == null)
            {
                return NotFound();
            }

thelibraryproject/thelibrary/Views/Author/BookByAuthor.cshtml
@model IEnumerable<BookAuthor>

@*<h1>Books in @Model.</h1>
*@
@foreach (var book in Model)
{
    
    @*<h2> </h2>*@
    <h3>@Html.ActionLink(book.Book.Title, "Detail", "Book", new { Id = book.BookId }, null)</h3>
    @*<p>Author: @book.BookAuthors</p>*@
    <!-- Display other book information -->
    <hr />
}

thelibraryproject/thelibrary/Views/Author/Create.cshtml
@using thelibrary.Data.enums;
@using thelibrary.ViewModel;
@model AuthorViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-action="Create" enctype="multipart/form-data">
       <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Biography">Biography</label>
        <input asp-for="Biography" class="form-control" placeholder="Biography">
        <span asp-validation-for="Biography" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Sex">Sex</label>
        <select asp-for="Sex" asp-items="@Html.GetEnumSelectList<sex>()"  class="form-control" placeholder="Sex">
            <option>--Select--</option>
        </select>
    </div> 

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

thelibraryproject/thelibrary/Views/Author/Edit.cshtml
@using thelibrary.Data.enums;
@using thelibrary.ViewModel;
@model AuthorViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-action="Edit" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Biography">Biography</label>
        <input asp-for="Biography" class="form-control" placeholder="Biography">
        <span asp-validation-for="Biography" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Sex">Sex</label>
        <select asp-for="Sex" asp-items="@Html.GetEnumSelectList<sex>()" class="form-control" placeholder="Sex">
            <option>--Select--</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

thelibraryproject/thelibrary/Views/Author/Index.cshtml
@model IEnumerable<Author>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Authors</h1>
        @*<p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>*@
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <p class="card-text">@item.Name</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>

                                    <a asp-controller="Author" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

thelibraryproject/thelibrary/Views/Author/UserIndex.cshtml
@model IEnumerable<Author>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Authors</h1>
        @*<p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>*@
    </div>
</section>

<div class="album py-5 bg-light">
    @*<a asp-controller="Author" asp-action="Create" asp-route-id="" class="btn btn-sm btn-outline-secondary">Create Author</a>*@
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <p class="card-text">@item.Name</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-controller="Author" asp-action="BookByAuthor" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">View</a>

                                    @*<a asp-controller="Author" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>*@
                                </div>
                                <small class="text-muted"></small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>