thelibraryproject/thelibrary/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace thelibrary.Models
{
    public class Category
    {
        [Key]
        public int CategoryId { get; set; }
        public string Name { get; set; }

        //books

        public ICollection<Book> Books { get; set; }
    }
}

thelibraryproject/thelibrary/Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using System.Net;
using thelibrary.Data;
using thelibrary.Map;
using thelibrary.Migrations;
using thelibrary.Models;
using thelibrary.Repository;
using thelibrary.Services;
using thelibrary.ViewModel;
using static System.Reflection.Metadata.BlobBuilder;

namespace thelibrary.Controllers
{
    public class BookController : Controller
    {
        private readonly LibraryDbContext _dbContext;
        private readonly IBookRepository _bookRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IPhotoService _photoService;
        private readonly IAuthorRepository _authorRepository;
        private readonly UserManager<Users> _userManager;

        public BookController(LibraryDbContext dbContext, UserManager<Users> userManager, IAuthorRepository authorRepository, IBookRepository bookRepository, IPhotoService photoService, ICategoryRepository categoryRepository)
        {
            this._dbContext = dbContext;
            this._bookRepository = bookRepository;
            this._photoService = photoService;
            this._categoryRepository = categoryRepository;
            this._authorRepository = authorRepository;
            this._userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            
            var data = _bookRepository.GetBooks();
                return View(data);                      
            
        }

        public async Task<IActionResult> UserIndex()
        {

            var data = _bookRepository.GetBooks();
            return View(data);

        }

        public IActionResult Search(string searchTerm)
        {
            var books = _dbContext.Books
                .Where(b => b.Title.Contains(searchTerm) || b.Category.Name.Contains(searchTerm))
                .ToList();

            return View("SearchResults", books);
        }


        public async Task<IActionResult> GetUserId()
        {
           return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetUserId(string username)
        {
            
                var user = await _userManager.FindByNameAsync(username);

                if (user != null)
                {
                    ViewBag.UserId = user.Id;
                }
                else
                {
                    ViewBag.UserId = null; // User not found
                }

                return View(); // Return to the same form view
            
        }
        public async Task<IActionResult> Detail(int Id)
        {
            var getBook = await _bookRepository.GetBookById(Id);
            return View(getBook);
        }       

        public async Task<IActionResult> Create()
        {
            var model =  new BookViewModel();
            
            var categories = await _categoryRepository.GetAllCategories();
            var authors = await _authorRepository.GetAuthors();
            ViewBag.category = new SelectList(categories.ToList(), "Id", "Name");
            ViewBag.author = new MultiSelectList(authors.ToList(), "Id", "Name");


            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> Create(BookViewModel  model) 
        {
           
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Upload Failed"); 
                return View(model);
            }
            
            var result = await _photoService.AddPhotoAsync(model.ActualBook);

            var newBook = new Book()
            {
                Title = model.Title,
                Pages = model.Pages,
                BookSummary = model.BookSummary,
                ActualBook = result.Url.ToString(),
                CategoryId = model.CategoryId,
                
                
            };
            _bookRepository.Add(newBook);
            //_dbContext.SaveChanges();

            foreach (var id in model.AuthorId)
            {
                var _book_author = new BookAuthor()
                {
                    BookId = newBook.Id,
                    AuthorId = id
                };
                _dbContext.BookAuthors.Add(_book_author);
                _dbContext.SaveChanges();
            }
            return RedirectToAction("Index");
                                        
            

        }
        //[Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> Edit(int Id)
        {
            var getBook = await _bookRepository.GetBookById(Id);
            if (getBook == null) return View("Error");
            var categories = await _categoryRepository.GetAllCategories();
            var authors = await _authorRepository.GetAuthors();
            ViewBag.category = new SelectList(categories.ToList(), "Id", "Name");
            ViewBag.author = new MultiSelectList(authors.ToList(), "Id", "Name");
            var bookVM = getBook.Mapper();            
            return View(bookVM);

        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditBookViewModel model, int Id)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Edit Failed");
                return View("Edit", model);
            }
            else
            {
                var book = await _bookRepository.GetBookById(Id);
                if (book != null)
                {
                    try
                    {

                        await _photoService.DeletePhotoAsync(book.ActualBook);
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", "Couldn't Delete photos");
                        return View(model);
                    }
                    var photoresult = await _photoService.AddPhotoAsync(model.ActualBook);

                    book.Id = model.Id;
                    book.Title = model.Title;
                    book.Pages = model.Pages;
                    book.BookSummary = model.BookSummary;
                    book.ActualBook = photoresult.Url.ToString();
                    book.CategoryId = model.CategoryId;

                    if(model.AuthorId != null)
                    {
                        foreach (var id in model.AuthorId)
                        {
                            var _book_author = new BookAuthor()
                            {
                                BookId = book.Id,
                                AuthorId = id
                            };
                            _dbContext.BookAuthors.Add(_book_author);
                            _dbContext.SaveChanges();
                        }

                    }
                    _dbContext.SaveChanges();
                    _bookRepository.Update(book);                  
                    return RedirectToAction("Index");
                    }
                else
                {
                    return View(model);
                }

            }            

        }
        public async Task<IActionResult> Borrow(int bookId)
        {
            var book = await _dbContext.BookReservations.
                Include(r => r.Book).
                Include(r => r.User).
                FirstOrDefaultAsync(x => x.BookId == bookId);
            //var book = await _dbContext.Books.FirstOrDefaultAsync(b=>b.Id == bookId);
            if (book == null)
            {
                return NotFound();
            }

            var Borrow = new BorrowBook
            {
                BookId = bookId,
                
            };

            return View(Borrow);
            
        }

        [HttpPost]
        public async Task<IActionResult> Borrow(BorrowBook borrow)
        {
            var book = await _dbContext.Books.FirstOrDefaultAsync(x => x.Id == borrow.BookId);
            var reservation = _dbContext.BookReservations
            .Include(r => r.User) // Include the user information
            .FirstOrDefault(r => r.BookId == borrow.BookId);


            if (book != null && book.IsReserved== true)
            {

                var borrowedbook = new BorrowBook
                {
                    BookId = borrow.BookId,
                    UserId = reservation.UserId, // Replace with actual user name
                    BorrowDate = DateTime.Now,
                    ReturnDate = DateTime.Now.AddDays(14)
                };

                book.IsReserved = true;
                book.IsBorrowed = true;
                _dbContext.Booksborrowed.Add(borrowedbook);  
                _dbContext.SaveChanges();
               

               
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Return(BorrowBook borrow)
        {
            var borrowed = await _dbContext.Booksborrowed.FirstOrDefaultAsync(x => x.BookId == borrow.BookId);
            var book = _dbContext.Books.FirstOrDefault(b => b.Id == borrowed.BookId);

            if (borrowed != null && book.IsBorrowed == true )
            {
                
                if (book != null)
                {
                    book.IsReserved = false;
                    book.IsBorrowed = false;
                    //_dbContext.Booksborrowed.Remove(borrow);
                    _dbContext.SaveChanges();


                }                
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Reserve(int bookId)
        {

            var book = await _dbContext.Books.FirstOrDefaultAsync(x => x.Id == bookId);            
            if (book == null)
            {
                return NotFound();
            }

thelibraryproject/thelibrary/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using thelibrary.Data;
using thelibrary.Map;
using thelibrary.Models;
using thelibrary.Repository;
using thelibrary.ViewModel;

namespace thelibrary.Controllers
{
    public class CategoryController : Controller
    {

        private readonly LibraryDbContext _dbContext;
        private readonly ICategoryRepository _categoryRepository;
        public CategoryController(LibraryDbContext dbContext, ICategoryRepository categoryRepository)
        {
            _dbContext = dbContext;
            this._categoryRepository = categoryRepository;

        }
        public async Task<IActionResult> Index()
        {
            var allCategories =await _dbContext.Categories.ToListAsync();
            return View(allCategories);
        }

        public async Task<IActionResult> UserIndex()
        {
            var allCategories = await _dbContext.Categories.ToListAsync();
            return View(allCategories);
        }

        [HttpGet]
        public async Task<IActionResult> GetAllCategories()
        {
            var allCategories = await _dbContext.Categories.ToListAsync();
            return View(allCategories);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(CategoryViewModel category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            else
            {
                var exist = _dbContext.Set<Category>().Where(c => c.Name == category.Name).FirstOrDefault();
                if(exist != null)
                {
                    return View("Error");
                }

                _categoryRepository.Add(category);
                return RedirectToAction("Index");
            }      
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var getcategory = await _categoryRepository.GetCategoryById(Id);
            if (getcategory == null) return View("Error");
            
            return View(getcategory);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Edit Failed");
                return View("Edit", model);
            }
            else
            {
                var acategory  = await _categoryRepository.GetCategoryById(model.Id);
                if (acategory != null)
                {
                    acategory.CategoryId= model.Id;
                    acategory.Name = model.Name;               
                    
                    _categoryRepository.Update(acategory);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }

            }

        }

        public IActionResult BooksByCategory(int CategoryId)
        {
            var category = _dbContext.Categories.Include(c => c.Books).FirstOrDefault(c => c.CategoryId == CategoryId);
            return View(category);
        }


    }
}

thelibraryproject/thelibrary/Views/Category/BooksByCategory.cshtml
@model Category

<h1>Books in @Model.Name</h1>

@foreach (var book in Model.Books)
{
    <h3>@Html.ActionLink(book.Title, "Detail", "Book", new { Id = book.Id }, null)</h3>
    @*<p>Author: @book.BookAuthors</p>*@
    <!-- Display other book information -->
    <hr />
}

thelibraryproject/thelibrary/Views/Category/Create.cshtml
@model Category
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Create">
  <div class="form-group">
    <label asp-for="Name">Name</label>
    <input asp-for="Name" class="form-control" placeholder="Name">  
    <span asp-validation-for="Name" class="text-danger"></span>
  </div>
  
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

thelibraryproject/thelibrary/Views/Category/Edit.cshtml
@model Category
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Edit" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>

thelibraryproject/thelibrary/Views/Category/Index.cshtml
@model IEnumerable<Category>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="jumbotron text-center">
    <div class="container">
        <a asp-controller="Home" asp-action="Index" asp-route-id="" class="btn btn-sm btn-outline-secondary">Back Home</a>
        <h1 class="jumbotron-heading">Category</h1>
        @*<a asp-controller="Category" asp-action="Create"  class="btn btn-sm btn-outline-secondary">New</a>*@
        @*<p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
            <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>*@
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">                        
                        <div class="card-body">
                            <p class="card-text">@item.Name</p>                            
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    @*<a asp-controller="Category" asp-action="BooksByCategory" ,new { categoryId = item.CategoryId }, null ,class="btn btn-sm btn-outline-secondary">Detail</a>*@
                                    <a href="@Url.Action("BooksByCategory", "Category", new { item.CategoryId})" class="btn btn-sm btn-outline-secondary">Deatil</a>
                                    <a asp-controller="Category" asp-action="Edit" asp-route-id="@item.CategoryId" class="btn btn-sm btn-outline-secondary">Edit</a>
                                    
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

thelibraryproject/thelibrary/Views/Category/UserIndex.cshtml
@model IEnumerable<Category>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Category</h1>
        @*<p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>*@
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <p class="card-text">@item.Name</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    @*<a asp-controller="Category" asp-action="BooksByCategory" ,new { categoryId = item.CategoryId }, null ,class="btn btn-sm btn-outline-secondary">Detail</a>*@
                                    <a href="@Url.Action("BooksByCategory", "Category", new { item.CategoryId})" class="btn btn-sm btn-outline-secondary">Deatil</a>
                                    @*<a asp-controller="Category" asp-action="Edit" asp-route-id="@item.CategoryId" class="btn btn-sm btn-outline-secondary">Edit</a>*@

                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>